import { Recipe, Category, User } from '@/types';

export const currentUser: User = {
  id: 'current-user-1',
  email: 'user@example.com',
  username: 'foodie_chef',
  full_name: 'Chef Master',
  avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face',
  bio: 'Passionate home chef sharing delicious recipes',
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

export const recipes: Recipe[] = [
  {
    id: '1',
    title: 'Creamy Mushroom Risotto',
    description: 'A rich and creamy risotto with wild mushrooms and parmesan cheese',
    ingredients: ['Arborio rice', 'Wild mushrooms', 'Parmesan cheese', 'White wine', 'Vegetable broth'],
    instructions: ['Sauté mushrooms', 'Toast rice', 'Add broth gradually', 'Stir in cheese'],
    prep_time: 15,
    cook_time: 30,
    servings: 4,
    difficulty: 'medium',
    image_url: 'https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=400&h=300&fit=crop',
    created_by: currentUser.id,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    is_favorited: false,
    likes_count: 124,
    comments_count: 18,
    author: {
      id: currentUser.id,
      username: currentUser.username,
      full_name: currentUser.full_name,
      avatar_url: currentUser.avatar_url,
    },
  },
  {
    id: '2',
    title: 'Spicy Thai Basil Chicken',
    description: 'Authentic Thai stir-fry with fresh basil and chilies',
    ingredients: ['Chicken breast', 'Thai basil', 'Chilies', 'Fish sauce', 'Garlic'],
    instructions: ['Marinate chicken', 'Heat wok', 'Stir-fry ingredients', 'Add basil'],
    prep_time: 20,
    cook_time: 15,
    servings: 2,
    difficulty: 'easy',
    image_url: 'https://images.unsplash.com/photo-1559847844-d721426d6edc?w=400&h=300&fit=crop',
    created_by: currentUser.id,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    is_favorited: true,
    likes_count: 89,
    comments_count: 12,
    author: {
      id: currentUser.id,
      username: currentUser.username,
      full_name: currentUser.full_name,
      avatar_url: currentUser.avatar_url,
    },
  },
  {
    id: '3',
    title: 'Classic Chocolate Chip Cookies',
    description: 'Soft and chewy cookies with premium chocolate chips',
    ingredients: ['Flour', 'Butter', 'Brown sugar', 'Chocolate chips', 'Vanilla'],
    instructions: ['Cream butter and sugar', 'Add dry ingredients', 'Fold in chips', 'Bake until golden'],
    prep_time: 15,
    cook_time: 12,
    servings: 24,
    difficulty: 'easy',
    image_url: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=400&h=300&fit=crop',
    created_by: currentUser.id,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    is_favorited: false,
    likes_count: 156,
    comments_count: 23,
    author: {
      id: currentUser.id,
      username: currentUser.username,
      full_name: currentUser.full_name,
      avatar_url: currentUser.avatar_url,
    },
  },
];

export const categories: Category[] = [
  {
    id: '1',
    name: 'Breakfast',
    icon: '☕',
    color: '#FACC15',
    recipe_count: 45,
    description: 'All about breakfast recipe tutorial',
  },
  {
    id: '2',
    name: 'Desserts',
    icon: '🍩',
    color: '#8B5CF6',
    recipe_count: 32,
    description: 'Sweet treats and desserts',
  },
  {
    id: '3',
    name: 'Main Course',
    icon: '🍽️',
    color: '#10B981',
    recipe_count: 78,
    description: 'Hearty main dishes',
  },
  {
    id: '4',
    name: 'Appetizers',
    icon: '🥗',
    color: '#F59E0B',
    recipe_count: 23,
    description: 'Light starters and snacks',
  },
  {
    id: '5',
    name: 'Beverages',
    icon: '🥤',
    color: '#EF4444',
    recipe_count: 19,
    description: 'Refreshing drinks',
  },
  {
    id: '6',
    name: 'Soups',
    icon: '🍲',
    color: '#3B82F6',
    recipe_count: 34,
    description: 'Warm and comforting soups',
  },
];